from pathlib import Path
path = Path(r"C:\Users\shane\OneDrive\Code\Grouper\GroupProjectAI\app\project\[id].tsx")
data = path.read_text(encoding='utf-8')
start_marker = "\t\t\t\t\t{/* Project title + meta"
start = data.index(start_marker)
end_marker = "\t\t\t\t\t</View>\n\n"
end = data.index(end_marker, start) + len(end_marker)
new_block = "\t\t\t\t\t{/* Project title + meta — two-column on wide */}\n"
new_block += "\t\t\t\t\t<View style={[{ marginBottom: 14 }, isWide && { flexDirection: \"row\", gap: 20, alignItems: \"flex-start\" }]}>{\n"
new_block += "\t\t\t\t\t\t<View style={isWide ? { flex: 1 } : {}}>{\n"
new_block += "\t\t\t\t\t\t\t<Text style={[styles.title, { color: textColor }]}>{project.name}</Text>{\n"
new_block += "\t\t\t\t\t\t\t<View style={{ flexDirection: \"row\", alignItems: \"center\", marginTop: 10, flexWrap: \"wrap\", gap: 8 }}>{\n"
new_block += "\t\t\t\t\t\t\t\t<View style={styles.pill}>{\n"
new_block += "\t\t\t\t\t\t\t\t\t<Text style={styles.pillText}>{formatTimeframe(project.timeframe)}</Text>{\n"
new_block += "\t\t\t\t\t\t\t\t</View>{\n"
new_block += "\t\t\t\t\t\t\t\t<Text style={{ color: mutedColor }}>{remainingTasksCount} tasks remaining</Text>{\n"
new_block += "\t\t\t\t\t\t\t\t{project?.plan_status && project.plan_status !== \"ready\" ? ({\n"
new_block += "\t\t\t\t\t\t\t\t\t<View style={{\n"
new_block += "\t\t\t\t\t\t\t\t\t\tbackgroundColor: project.plan_status === \"failed\" ? \"#FEE2E2\" : \"#FEF9C3\",\n"
new_block += "\t\t\t\t\t\t\t\t\t\tpaddingHorizontal: 10, paddingVertical: 4, borderRadius: 999,\n"
new_block += "\t\t\t\t\t\t\t\t\t}}>{\n"
new_block += "\t\t\t\t\t\t\t\t\t\t<Text style={{ color: project.plan_status === \"failed\" ? \"#991B1B\" : \"#854D0E\", fontSize: 12, fontWeight: \"700\" }}>{\n"
new_block += "\t\t\t\t\t\t\t\t\t\t\t{project.plan_status === \"pending\" ? \"Generating plan…\" : \"Plan failed\"}\n"
new_block += "\t\t\t\t\t\t\t\t\t\t</Text>{\n"
new_block += "\t\t\t\t\t\t\t\t\t</View>{\n"
new_block += "\t\t\t\t\t\t\t\t) : null}{\n"
new_block += "\t\t\t\t\t\t\t</View>{\n"
new_block += "\t\t\t\t\t\t\t{!isWide ? renderPeopleSection() : null}{\n"
new_block += "\t\t\t\t\t\t</View>{\n"
new_block += "\t\t\t\t\t\t{isWide ? ({\n"
new_block += "\t\t\t\t\t\t\t<View style={{ flex: 1, gap: 12 }}>{\n"
new_block += "\t\t\t\t\t\t\t\t{showDescriptionCard ? ({\n"
new_block += "\t\t\t\t\t\t\t\t\t<View style={{ backgroundColor: cardBg, borderRadius: 12, padding: 14 }}>{\n"
new_block += "\t\t\t\t\t\t\t\t\t\t<Text style={{ fontWeight: \"700\", color: colors.pennRed, marginBottom: 6, fontSize: 13 }}>Description</Text>{\n"
new_block += "\t\t\t\t\t\t\t\t\t\t<Text style={{ color: mutedColor, lineHeight: 20, fontSize: 13 }} numberOfLines={4}>{\n"
new_block += "\t\t\t\t\t\t\t\t\t\t\t{descriptionText}\n"
new_block += "\t\t\t\t\t\t\t\t\t\t</Text>{\n"
new_block += "\t\t\t\t\t\t\t\t\t</View>{\n"
new_block += "\t\t\t\t\t\t\t\t) : null}{\n"
new_block += "\t\t\t\t\t\t\t\t{renderPeopleSection(0)}\n"
new_block += "\t\t\t\t\t\t\t</View>{\n"
new_block += "\t\t\t\t\t\t) : null}{\n"
new_block += "\t\t\t\t\t\t</View>{\n"
new_block += "\t\t\t\t\t</View>{\n\n"
new_data = data[:start] + new_block + data[end:]
path.write_text(new_data, encoding='utf-8')
